### ISSUE TITLE
Videos taking 30 seconds to load, and then they sttuter

### ISSUE THREAD

**Issue by slypire** [gupekmop/youtube#6]
As of recently, when I try to load videos, it takes about 30 seconds for it load, and after it loads its sttutering like crazy, tried to reboot the device, etc, nothing helps, any ideas what could be the problem?
I'm using latest version.

**Comment by gupekmop** [comment]
No ideas, maybe Google make temporary troubles...

**Comment by rajaie1976** [comment]
same here , videos seems to detect the type of device and block through the API

**Comment by rajaie1976** [comment]
I fount that the video less than 600kb/s will work , and above that will not work correctly , 
this means that youtube is limitting the application or the scheam or the device or the nature of the request to max 600kb/s .
the issue is it is needed to request the video format in less than 600kb/s

does youtube api support something like that ?

**Comment by bokcep** [comment]
Да было бы не плохо сделать принудительно воспроизведение видео хотя бы в 600kb/s, а то смотреть не возможно!
Yes, it would not be bad to force video playback at least 600kb / s, otherwise it is not possible to watch!
